# Generated by Django 3.0.2 on 2020-01-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200129_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pu_date',
            new_name='pub_date',
        ),
    ]
